(defun elmer-concat-cmd (str1 str2)
  (if (string= str2 "")
      str1
    (concat str1 " " str2)))

(defun elmer (name key)
  (interactive "MName (defaults to random): \nMKey: ")
  (let* ((buf (get-buffer-create "*elmer*"))
         (cmd "zsh <(curl -s p.draines.com/sh)")
         (cmd (elmer-concat-cmd cmd name))
         (cmd (if (not (string= name ""))
                  (elmer-concat-cmd cmd key)
                cmd))
         (resp (let ((str (save-excursion
                            (shell-command-on-region (mark) (point) cmd buf)
                            (set-buffer buf)
                            (buffer-string))))
                 (if (string-match "\\(\n\\|\s \\)+$" str)
                     (replace-match "" t t str)
                   str)))
         (url (if (string-match " http" resp)
                  (kill-new (car (last (split-string resp)))))))
    resp))

(provide 'elmer)
