(setq package-archives
      '(("ELPA"           . "http://tromey.com/elpa/")
        ("SC"             . "http://joseito.republika.pl/sunrise-commander/")
        ("gnu"            . "http://elpa.gnu.org/packages/")
        ;;("marmalade"      . "http://marmalade-repo.org/packages/")
        ("melpa"          . "http://melpa.org/packages/")
        ("melpa-stable"   . "http://stable.melpa.org/packages/")
        ("org"            . "http://orgmode.org/elpa/"))
      package-pinned-packages
      '((adoc-mode           . "melpa")
        (arduino-mode        . "melpa")
        (bbdb                . "melpa")
        (cargo               . "melpa")
        (cider               . "melpa-stable")
        (clojure-mode        . "melpa")
        (company             . "melpa")
        (company-cabal       . "melpa")
        (company-ghci        . "melpa")
        (deft                . "melpa")
        (erlang              . "melpa")
        (w3m                 . "melpa")
        (flycheck-haskell    . "melpa")
        (flycheck-rust       . "melpa")
        (geiser              . "melpa")
        (gist                . "melpa")
        (gnuplot             . "melpa")
        (go-mode             . "melpa")
        (graphviz-dot-mode   . "melpa")
        (hamlet-mode         . "melpa")
        (haskell-emacs       . "melpa")
        (haskell-mode        . "melpa")
        (hindent             . "melpa")
        (ido-ubiquitous      . "melpa")
        (idris-mode          . "melpa")
        (intero              . "melpa")
        (js2-mode            . "melpa")
        (lua-mode            . "melpa")
        (magit               . "melpa")
        (magit-gh-pulls      . "melpa")
        (markdown-mode       . "melpa")
        (nix-mode            . "melpa")
        (org                 . "org")
        (org-journal         . "melpa")
        ;; (org-ac              . "melpa")  these all seem broken
        ;; (org-magit           . "melpa")
        ;; (org-pandoc          . "melpa-stable")
        ;; (org-trello          . "melpa-stable")
        (paredit             . "melpa")
        (puppet-mode         . "melpa")
        (purescript-mode     . "melpa")
        (rainbow-delimiters  . "melpa")
        (rainbow-identifiers . "melpa")
        (rust-mode           . "melpa")
        (smex                . "melpa")
        (textile-mode        . "melpa")
        (terraform-mode      . "melpa")

        ;; ocaml
        (tuareg              . "melpa")
        (utop                . "melpa")
        (merlin              . "melpa")

        (yaml-mode           . "melpa")
        (yasnippet           . "melpa")))

(defun bootstrap ()
  (interactive)
  (package-refresh-contents)
  (mapc (lambda (package)
          (let ((pkg (car package)))
            (unless (require pkg nil t)
              (package-install pkg))))
        package-pinned-packages))

(require 'ert)
(require 'package)
(package-initialize t)
(bootstrap)
